name: Deploy to Kubernetes

on:
  push:
    branches: ['main']
  pull_request:
    branches:  none # ['main'] dont build and push an image when pull request

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set K8s context
      uses: ossrs/k8s-set-context-action@v1
      with:
        kubeconfig: '${{ secrets.KUBE_CONFIG }}'
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${KUBE_CONFIG} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Deploy to K8s
      run: kubectl apply -f deployment.yaml
