# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: ci/cd pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches:  none # ['main'] dont build and push an image when pull request

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # in this case will be samer955/book-example
  IMAGE_TAG: 1.0.${{ github.run_number }} # it will increase the tag number on every push starting from 1.0.0

jobs:

  build-push-docker:
  
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
    - uses: actions/checkout@v3  # Checkout the repository

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build # Build the Go Code
      run: go build -v ./...

    - name: Test  # Test the go Code
      run: go test -v ./...
      
    - name: Set up Docker Buildx # setup for the docker container 
      uses: docker/setup-buildx-action@v2
      
    - name: Deploy to K8s
      run: kubectl apply -f deployment.yaml
      
    - name: Display pods
      run: kubectl get pods -A
